import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import './globals.css';
import CartProvider from './components/Provider';
import ShoppingCartModal from './components/ShopingCartModal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <CartProvider>
                    <Navbar />
                    <ShoppingCartModal />
                    {children}
                </CartProvider>
            </body>
        </html>
    );
}
